app/home/forms.py
# app/admin/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from ..models import User

class NoteForm(FlaskForm):
    """
    Form for normal user to add or edit a note
    """
    noteText = StringField('Note text', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/home/__init__.py
# app/home/__init__.py

from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
# app/home/views.py

from flask import flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import home
from forms import NoteForm
from .. import db
from ..models import Note, User

@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title="Welcome")

@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")

# add admin dashboard view
@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    # prevent non-admins from accessing the page
    if not current_user.is_admin:
        abort(403)

    return render_template('home/admin_dashboard.html', title="Dashboard")

@home.route('/notes', methods=['GET', 'POST'])
@login_required
def list_notes():
    """
    List all notes
    """

    notes = Note.query.all()
    notes = [note for note in notes if note.user_id == current_user.id]

    return render_template('home/notes/notes.html',
                           notes=notes, title="Notes")

@home.route('/notes/add', methods=['GET', 'POST'])
@login_required
def add_note():
    """
    Add a note to the database
    """

    add_note = True

    form = NoteForm()
    if form.validate_on_submit():
        note = Note(user_id=current_user.id, text=form.noteText.data)
        try:
            # add note to the database
            db.session.add(note)
            db.session.commit()
            flash('You have successfully added a new note.')
        except:
            flash('Note cannot be added.')
            db.session.rollback()

        # redirect to notes page
        return redirect(url_for('home.list_notes'))

    # load note template
    return render_template('home/notes/note.html', action="Add",
                           add_note=add_note, form=form,
                           title="Add Note")

@home.route('/notes/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_note(id):
    """
    Edit a note
    """

    add_note = False

    note = Note.query.get_or_404(id)
    form = NoteForm(obj=note)
    if form.validate_on_submit():
        note.user_id = current_user.id
        note.text = form.noteText.data
        db.session.commit()
        flash('You have successfully edited the note.')

        # redirect to the notes page
        return redirect(url_for('home.list_notes'))

    form.noteText.data = note.text
    # form.userEmail.data = note.user_id
    return render_template('home/notes/note.html', action="Edit",
                           add_note=add_note, form=form,
                           note=note, title="Edit Note")

@home.route('/notes/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_note(id):
    """
    Delete a note from the database
    """

    note = Note.query.get_or_404(id)
    db.session.delete(note)
    db.session.commit()
    flash('You have successfully deleted the note.')

    # redirect to the notes page
    return redirect(url_for('home.list_notes'))

    return render_template(title="Delete Note")

app/templates/home/notes/note.html
<!-- app/templates/home/note/note.html -->

{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_note %}
        Add Note
    {% else %}
        Edit Note
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_note %}
                <h1>Add Note</h1>
            {% else %}
                <h1>Edit Note</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/notes/notes.html
<!-- app/templates/home/notes/notes.html -->

{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Notes{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Notes</h1>
        {% if notes %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="40%"> Text </th>
                  <th width="15%"> Edit </th>
                  <th width="15%"> Delete </th>
                </tr>
              </thead>
              <tbody>
              {% for note in notes %}
                <tr>
                  <td> {{ note.text }} </td>
                  <td>
                    <a href="{{ url_for('home.edit_note', id=note.id) }}">
                      <i class="fa fa-pencil"></i> Edit 
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('home.delete_note', id=note.id) }}">
                      <i class="fa fa-trash"></i> Delete 
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No notes have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('home.add_note') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Note
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}